### ISSUE TITLE
Clicking on apps don't hide them

### ISSUE THREAD

**Issue by Deykii** [ramensoftware/windows-11-taskbar-styling-guide#126]
Yeah, as I said in the name, clicking on apps' icons don't hide them, but  when I turn taskbar costomizer off it works properly

**Comment by bbmaster123** [comment]
[this?](https://www.ashampoo.com/en-us/taskbar-customizer)
It's probably conflicting since the styler mod and this program both are trying to modify the taskbar. Several other TB mod apps are also known to conflict in various ways.
 
I can only suggest to disable other taskbar modding apps when using taskbar styler, unless you can be sure both work together

I must ask - why are you trying to use both? what does taskbar customizer do that you can't do in the styler?
cheers

**Comment by m417z** [comment]
That sounds similar to this issue: https://github.com/ramensoftware/windhawk-mods/issues/1141

See [my reponse](https://github.com/ramensoftware/windhawk-mods/issues/1141#issuecomment-2439466926), If that's the issue, the only workaround for now is to disable the problematic style.

**Comment by Deykii** [comment]
> That sounds similar to this issue: [ramensoftware/windhawk-mods#1141](https://github.com/ramensoftware/windhawk-mods/issues/1141)
> 
> See [my reponse](https://github.com/ramensoftware/windhawk-mods/issues/1141#issuecomment-2439466926), If that's the issue, the only workaround for now is to disable the problematic style.

I guess thats because I installed a mod that makes scrolling mouse wheel open and minimize the tasks. Thanks for responses!!!
